### ISSUE TITLE
NLA support when we control the destination server

### ISSUE THREAD

**Issue by xiaoweigege** [GoSecure/pyrdp#134]
How to implement client in connection honeypot service, let client input username, password

**Comment by Pourliver** [comment]
The client has to input his username and password when attempting connection. If your server is using NLA and your RDP client supports it, you will be prompted to enter username, password, and domain. If you're not using NLA, you will get to a standard Windows login screen.

Does that answer your question? Sorry if I misinterpreted it!

**Comment by xiaoweigege** [comment]
At present, I am using your pyrdp server, and the client USES Windows remote connection client. In fact, what I need is to prompt for the user name and password when Windows remote connection client connects to pyrdp server, but there seems to be no introduction of this part in the source code. Thank you

**Comment by Res260** [comment]
The mstsc rdp client does not prompt for user and password upon connection
if NLA is disabled, if I remember correctly. PyRDP doesnt currently support
NLA, so this would be why the mstsc client doesnt behave the way you want.

**Comment by xiaoweigege** [comment]
How can I support NLA? Will this feature be added in the next release? If there is a solution, I would like to try to add this feature. thank you @Res260

**Comment by Res260** [comment]
Partial NLA support has been discussed as an idea, but no one is working on it right now, as it requires non-trivial changes to pyrdp.

**Comment by xiaoweigege** [comment]
If NLA is supported, it will be more realistic as a honeypot system, and it can effectively know whether the password of the internal server of the company is leaked by employees. This is a good idea. Come on! Looking forward to!

**Comment by obilodeau** [comment]
It has been a while since we discussed this internally but the only way we could support NLA is if the server's certificate and it's private key is extracted from it and given to PyRDP. We studied this protocol for a while and that was our conclusion. This is because the certificate's fingerprint inside the Net-NTLM exchange is encrypted and HMAC'ed by the client (with the servers' token) and compared by both sides. So the TLS layer certificate fingerprint (which we MITM) must match information into the Net-NTLM layer which is encrypted by credentials we still don't have access to.

I agree that for a honeypot it could work since we control the destination server and we can even stuff our own credentials but in pentest scenarios, it is not the case.

For pentest, now we want to redirect clients to a machine we control that doesn't do NLA. Client-side  NLA enforcement is off by default and it's not even possible to enforce NLA from the UI.

If you are interested in contributing NLA support we would love to! Here are some acronyms and relationships between them in order to get you started:

![rdp](https://user-images.githubusercontent.com/546325/61303928-54cb3200-a7b6-11e9-8f93-8018329d5258.jpg)

**Comment by xiaoweigege** [comment]
I think it's a good idea and I'm happy to give it a try.

**Comment by alxbl** [comment]
This will now be supported once #229 lands, but it will require extracting the destination server's private key, as we do not currently implement processing of the CredSSP handshake. With the private key however, it is possible to let CredSSP opaquely pass through PyRDP, which makes NLA possible in honeypot scenarios.

We might eventually revisit full CredSSP support, but this is not on the roadmap at the moment.
