### ISSUE TITLE
Implement the drawing orders (GDI) API for output packets

### ISSUE THREAD

**Issue by xshill** [GoSecure/pyrdp#153]
Following from [this Twitter conversation](https://twitter.com/therealshodan/status/1176891723290689537) and [this gist comment](https://gist.github.com/xshill/a4a41b76bb980f766657a2828989c84a#gistcomment-3037754).

Currently, we can only create replays from PCAPs when the RDP session uses bitmap output. Implementing the GDI drawing order packets (the "normal" output method) would allow the pyrdp-replay script to work with any kind of RDP pcap. It would be nice to have, unfortunately there's quite a bit of work to do to get there.

For reference, here is the spec for drawing orders:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegdi/745f2eee-d110-464c-8aca-06fc1814f6ad

And the Graphics Update PDU structure:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/bd3c4df4-87b9-43dd-88cb-ce5b24698e19

**Comment by robeving** [comment]
Alternatively are there ways to disable this on the server itself?

**Comment by obilodeau** [comment]
When PyRDP is doing the man-in-the-middle, it will downgrade these channels to bitmap so if you have a packet capture of that you will be able to extract a replay out of it.

Now, to your question: is it possible to disable it from the server? I'm not sure but I would suspect it would be hard to do without modifying system libraries.

I don't know much about your use case but an alternative would be to run `pyrdp-mitm.py` combined with bettercap and poison clients trying to reach that server's IP. If you control the server you could even [extract the server's certificate and private key](https://superuser.com/a/939224) and use them in PyRDP making this transparent to users who trust the server. For certificate extraction and re-use, we know its possible but never did it ourselves so step-by-step documentation contribution would be appreciated.

**Comment by Res260** [comment]
This is a duplicate for #50 :)

**Comment by robeving** [comment]
For me, the **most** important thing is to not have a protocol break. I want the clients to have access to the full range of features RDP offers. For instance if an attacker was to use something like CVE-2019-0708 then pyrdp may have altered the connection so that the attack is not successful.

As for dumping the RDP key from a recent version of Windows:
- First you need to disable all algorithms that use ephemeral keys (Diffie-Hellman, probably anything that uses Elliptic curve). This is done by removing certain algorithms from SCHANNEL, the Windows crypto provider. There is a tool https://www.nartac.com/Products/IISCrypto/ which gives a nice GUI.
- Reboot box, check with Wireshark that TLS + RSA is in use.
- Use Mimikatz to dump the RDP certificates - https://github.com/FreeRDP/FreeRDP/wiki/Mimikatz

**Comment by Res260** [comment]
For reference, bitmap and gdi are not the only ways to transfer graphics via RDP. Most recent RDP versions use RemoteFx.

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdprfx/62495a4a-a495-46ea-b459-5cde04c44549

**Comment by robeving** [comment]
You can disable RemoteFx via the registry / group policy.

**Comment by alxbl** [comment]
I've started looking into this, I'm going to close this issue as a duplicate of #50 since it's been around longer, but this issue's discussion has a lot of interesting information that will be useful to keep in mind.

Cheers,
