### ISSUE TITLE
Document the extraction of trusted certificate from Windows destination RDP to avoid untrusted certs errors

### ISSUE THREAD

**Issue by SnasiCze** [GoSecure/pyrdp#154]
I have access to the rdp server and need to clone / export a trusted certificate
I tried:
- pyrdp-clonecert.py
- Export certificate from server without key.
- Export certificate and key from server using mimikatz
- Export the certificate from the mitm server and run pyrdp-mitm with this certificate and key.

The certificate has always been untrusted!
How do I clone a certificate to be trusted?

**Comment by xshill** [comment]
There seems to be a common misunderstanding that `pyrdp-clonecert.py` should generate a trusted certificate. It can't, the tool is only used to create a brand new (i.e: untrusted) certificate with sensible values for things such as the common name, etc. so that you don't have to do it manually. In other words, it creates an untrusted certificate that **looks** like it makes sense within an organization.

We should probably add a warning to the README to make this clear.

As for why the other methods of exporting a certificate haven't produced a trusted certificate, I'm not exactly sure.

**Comment by alxbl** [comment]
Another interesting thing to note is that by default, RDP certificates are Trust-on-First-use, so unless you have a proper PKI deployed, it could be that the server certificate is not trusted to begin with.  Will clarify the documentation to explain those cases.
