### ISSUE TITLE
Enhanced RDP Security - failed negotitation

### ISSUE THREAD

**Issue by natan04** [GoSecure/pyrdp#168]
pyrdp fails to negotiate with the server and prints the follow error: 

The server failed the negotiation. Error: The server requires that the client support Enhanced RDP Security (section 5.4) with CredSSP (section 5.4.5.2).

Without pyrdp as man in the middle, the negotiation works perfectly.
does pyrdp support the CredSSP protocol?  Do I need to configure the pyrdp differently?

Thank you

**Comment by Res260** [comment]
Hi @natan04 

Network-Level Authentication (NLA) is an RDP feature that aims to mitigate Man-In-The-Middle (MITM) attacks. It uses CredSSP, hence why you see this error. 

This means that the destination server has NLA enabled (which is mostly a good thing, security-wise). PyRDP currently does **not** support NLA, but it could be implemented in the future. However, since NLA ensures that both the client and the server are aware of the credentials before initiating the connection, we need to control the destination server in order for it to work. Just to be clear, this is currently **not** implemented right now.

If you want to play with PyRDP and you control the destination server, you can Disable NLA in the Windows Settings.
