### ISSUE TITLE
Unable to obtain the password from the RDP client (Windows 7+)

### ISSUE THREAD

**Issue by jiacheng9966** [GoSecure/pyrdp#179]
By default, the built-in rdp client of win7 or above will not send the saved account password when connecting. . How can I solve this problem? Can setting gpedit.msc solve this problem?

**Comment by obilodeau** [comment]
We have regularly witnessed the opposite. Two options could explain that behavior:

* Are you connecting to a server that enforces NLA? [More information about NLA](https://github.com/GoSecure/pyrdp/issues/134)
* Is Restricted Admin enforced on the connecting side? [More information about Restricted Admin](https://labs.f-secure.com/blog/undisable/)

Can you verify and advise?

**Comment by obilodeau** [comment]
Also, if you are only interested in extracting the password from the client-side you should consider an alternative approach like https://github.com/0x09AL/RdpThief instead of doing it at the network-level.

Other alternatives exists: [powershell for RDG files](https://blog.prudhomme.wtf/use-powershell-to-decrypt-password-stored-in-a-rdg-file/) or [password recovery from network passwords](http://www.nirsoft.net/utils/network_password_recovery.html).

Note that I haven't tested nor do I endorse any of these tools.

**Comment by alxbl** [comment]
Hi @jiacheng9966. We recently discovered that credentials that were saved with CredSSP will not be sent by mstsc when the negotiated security is `TLS`. We believe this is a security measure that Microsoft put in place to prevent CredSSP -> TLS downgrade attacks.  You can try deleting the stored credentials and saving them while the MITM is active and see if that helps.

Feel free to re-open the issue if you believe that this is not the problem.
