### ISSUE TITLE
Make the input textbox vertical in pyrdp-player

### ISSUE THREAD

**Issue by Res260** [GoSecure/pyrdp#210]
With #208, putting the textbox vertical and on the right would use space more efficiently because most screens are 16:9 and some vertical space must be used by the player, this will most times leave empty space on the right:

![image](https://user-images.githubusercontent.com/14599855/78939758-b89f3480-7a82-11ea-9b2c-3f1a10a17232.png)

It also makes more sense since the data in it tends not to be large but long.

Thoughts?

**Comment by Res260** [comment]
thanks to my boy MSPaint here is a preview of the expected layout: 
![image](https://user-images.githubusercontent.com/14599855/78942663-24d06700-7a88-11ea-810f-50a62ab19d8c.png)

**Comment by alxbl** [comment]
It makes sense to have it vertical, since it's easier to have a widescreen aspect ratio. Feel free to prototype it and open a PR.

**Comment by alxbl** [comment]
We do not have the bandwidth for this. I'm going to close the issue to clean up the backlog, but if you end up implementing this, a PR is more than welcome, at which point you can link it with this issue and we can re-open until the PR is merged. I'll leave the `idea` tag on so that it can be easily searched for in the issue tracker.
