### ISSUE TITLE
nmap scan gives away linux attributes.

### ISSUE THREAD

**Issue by Norup123** [GoSecure/pyrdp#354]
Running pyrdp_mitm on an ubuntu 20.04 to a windows 10 machine, both in vmware.

Is this because i havnt cloned the windows certificates correctly, or how are you supposed to hide this?

![image](https://user-images.githubusercontent.com/54578187/131486799-6fabf6f8-a22d-454a-bb42-1fb7ab532815.png)

**Comment by obilodeau** [comment]
I believe the operating system detection of nmap works by looking at OS-specific data deep in the network stack. Like TCP sequence numbers, windows sizes, etc. This kind of information will be very difficult to change since it's deep in the linux kernel. 

You could try to run pyrdp on Windows instead. If you find any other way, please let us know we are interested to hear about it.
