### ISSUE TITLE
Add documentation on using PyRDP as a library

### ISSUE THREAD

**Issue by xshill** [GoSecure/pyrdp#62]
We should have documentation that explains how people can use PyRDP to create their own RDP-related tools. Here are a list of subjects that should be covered:

- The relations between PDU, Parser, Layer and Observer classes and their purpose
- A brief description of every package in pyrdp
- The connection sequence (more briefly than MSDN) along with a commented example script
- A brief explanation of MCS
- An explanation of the differences between all the security protocols that can be used (NLA protocols, TLS and RC4)
- Things that we circumvent in our MITM and that might need to be circumvented by other tools (e.g: NLA)

**Comment by bontchev** [comment]
It's been two years already - any progress in this aspect?

I am trying to make an RDP honeypot. So far I've made it using the RDPY library and it sort of works, but RDPY is buggy, messy, unsupported, Python2-only piece of crap and I am ashamed to release something that is this bad, even if the crap isn't in my code.

Problem is, I can't use your project "as is". It relies on having a MitM layer between the attacker and a real (or virtual) machine with exposed RDP. True, this allows you to monitor what the attacker does when they gain access, which is undoubtedly useful. However, one of the things they can do is attack other machines on the Internet from yours, and I cannot afford that.

I need a honeypot that accepts and logs the credentials (and other info, like IP address) used by the attacker but either denies access no matter what the credentials are, or plays a pre-recorded session (like the honeypot in RDPY does) without allowing the attacker to do anything.

Any pointers on how to achieve this?

**Comment by alxbl** [comment]
First off, there's a WIP PR (linked) that adds some level of documentation about the high level structure of PyRDP.

Secondly, I think there's a bit of confusion about the purpose of this issue. It is currently already possible to use/modify the PyRDP code to inject or modify packets, but there is no high level API to do so without diving into the PyRDP code. What this issue documents is the need for a high level client API which would allow PyRDP to be scripted as a client (login, send mouse clicks, keystrokes, etc.) without needing to understand the RDP internals.

Providing a server implementation that can send/spoof video or emulate/replace Windows is not in our goals.
There are also no plans to provide a similar high level API for the server right now, as the MITM code is fairly straightforward in most cases and can already be tapped by adding observers or additional PDU parsers. That is not to say that the API couldn't be improved, but this is currently not in our roadmap.

----

Now, as far as I can tell from your concerns, there are two ways you could approach your problem with PyRDP:
- Modify the codebase to automatically disconnect clients after the credential heuristic
- Put the honeypot behind a firewall that disallows outbound traffic.

The former is easier to implement (as simple as raising an exception after the heuristic logs the credentials) but means that PyRDP becomes fairly useless other than as a watering hole.

The latter is more involved at an infrastructure level, but would mean that you can still observe the actor's activity without risk of your server being used as a proxy. Essentially you would allow inbound RDP and disallow all outbound traffic other than what you need to administer the honeypot.

**Comment by Res260** [comment]
@bontchev I'm working on an unofficial (meaning there is no plan for it to be added to PyRDP's codebase and maintained), basic RDP server using the PyRDP codebase. If you only want to log credentials without actually committing to a working session, this could maybe work for you as well as give you the opportunity to extend it once you grasp how it interacts with the rest of the PyRDP codebase. It's not yet working, but hit me up if you're interested and I'll share it once it's in a working state. Otherwise I think Alex's ideas are pretty good.

**Comment by bontchev** [comment]
@Res260, yes, that would be good enough for me, so please notify me when it is ready.

The way I understand it, currently PyRDP translates all credentials entered by the attacker to the actual credentials of the machine that is being MitM-ed, so that any combination of credentials succeeds. It's probably possible to change that so that any credentials sent (including valid ones) are translated to credentials that don't work for the machine, so that the login attempt is always rejected.

I certainly understand that emulating a real server is way too difficult. I don't particularly insist on the ability to replay a pre-recorded session to the attacker (as the honeypot in RDPY does) - it won't fool a human attacker and bots don't care if you do it or not. So, just collecting the credentials should be good enough.

I don't want to allow the attacker to actually gain a foothold, period. I might make some mistake while firewalling the outbound traffic. And the firewall can't be that of the machine to which the attacker logs in, or he might be able to disable the restriction. So, I'd need a separate machine/router to block the outbound traffic. No, it's too risky and error-prone. Just collecting credentials and IP addresses will have to do.

However, it is important to me that I can use this as a library in my own project. My honeypot has its own structure, logging, etc. - I don't want to have to mess with the RDP layer, in order to do this the way I want it.
